// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTHmLuS9nv-ydue4wa_LP7pQXf9tChZA',
    appId: '1:965840683282:web:9e56829c729bb4ea01f3cb',
    messagingSenderId: '965840683282',
    projectId: 'todo-app-flutter-fed8e',
    authDomain: 'todo-app-flutter-fed8e.firebaseapp.com',
    storageBucket: 'todo-app-flutter-fed8e.firebasestorage.app',
    measurementId: 'G-2TLW4M7DBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh49_KyZ-Zyx4Om_nWWaQeLssIlJP51VQ',
    appId: '1:965840683282:android:8cd56ef252819d9001f3cb',
    messagingSenderId: '965840683282',
    projectId: 'todo-app-flutter-fed8e',
    storageBucket: 'todo-app-flutter-fed8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwkZUcHXpU-WktuU2T8sN2BtqRkVORDE',
    appId: '1:965840683282:ios:a1621f5ef525330d01f3cb',
    messagingSenderId: '965840683282',
    projectId: 'todo-app-flutter-fed8e',
    storageBucket: 'todo-app-flutter-fed8e.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjwkZUcHXpU-WktuU2T8sN2BtqRkVORDE',
    appId: '1:965840683282:ios:a1621f5ef525330d01f3cb',
    messagingSenderId: '965840683282',
    projectId: 'todo-app-flutter-fed8e',
    storageBucket: 'todo-app-flutter-fed8e.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTHmLuS9nv-ydue4wa_LP7pQXf9tChZA',
    appId: '1:965840683282:web:510c8b9530ff1b8c01f3cb',
    messagingSenderId: '965840683282',
    projectId: 'todo-app-flutter-fed8e',
    authDomain: 'todo-app-flutter-fed8e.firebaseapp.com',
    storageBucket: 'todo-app-flutter-fed8e.firebasestorage.app',
    measurementId: 'G-G8JN6MCCVE',
  );
}
